### ISSUE TITLE
Problem with working directory when attempting to knit

### ISSUE THREAD

**Issue by kelecss** [UniLuFS2020-ReplicationSeminar/Groupwork_Alluri_Hess_Lengwiler#4]
I merged the text and the code we have already written from the data_prep.R file and the Inference Statistics.R file into the Markdown_in process.Rmd file.

When trying to knit R can't find the dataset because somehow the working directory is set to: '/Users/kerimlengwiler/Desktop/R_Files/repo_CE1_1/Groupwork_Alluri_Hess_Lengwiler/**scripts**'

instead of '/Users/kerimlengwiler/Desktop/R_Files/repo_CE1_1/Groupwork_Alluri_Hess_Lengwiler/**original data**'

or even  '/Users/kerimlengwiler/Desktop/R_Files/repo_CE1_1/Groupwork_Alluri_Hess_Lengwiler'

which would correspond with the code to load the data:

data <- read_dta("data_original/ESS10.dta")

Do you know where the problem lies? Can you run the code?

**Comment by silvanhess** [comment]
Can't you just reset the working directory via Session -> Set Working Directory -> To Project Directory?

**Comment by kelecss** [comment]
I have tried to reset the working directory with setwd() but automatically goes back to '/Users/kerimlengwiler/Desktop/R_Files/repo_CE1_1/Groupwork_Alluri_Hess_Lengwiler/scripts'

Could you run it?

**Comment by silvanhess** [comment]
yes for me it works

**Comment by kelecss** [comment]
What is your working directory? Can you put in feted() and post the return that R gives for you?

**Comment by kelecss** [comment]
My work around is to setwd() whenever I load or store a dataset but that is of course not how it should be. Nevertheless if it works for you and you like the result we can go ahead and I can fix this another time instead of using our time on that matter.

**Comment by silvanhess** [comment]
thats okay, sorry i couldn't help
